// src/components/Home.vue
<template>
<section class="home-page container d-flex align-start justify-center col">
	<h2 class="header-primary">Hello 👋,</h2>
	<h1 class="header-primary">
		<span>I'm</span>
		<span class="name">Christian Valdez</span>
	</h1>
	<h2 class="subtitle">California Based Developer</h2>
	<a href="#" class="home-btn btn btn-primary my-1">
		About Me
		<i class="fa fa-chevron-circle-down" />
	</a>
</section>
</template>

<script>
export default {
	data() {
		return {
			subtitle: 'California Based Developer'
		}
	}
}
</script>

<style lang="scss" scoped>

i {
	padding: 0 0.5rem;
}

.subtitle {
	animation: slide-in-right ease-out .7s;
}

.home {
	&-page {
		height: 100vh;
	}
}

.name {
	background-image: linear-gradient(to right, $color-primary, $color-primary-light);
	-webkit-background-clip: text;
	color: transparent;
	padding: 0 2rem;
}

.header-primary {
	animation: slide-in-left ease-out .7s;
}

</style>

// src/app/_components/Home.tsx
"use client";
import React from "react";
import { scrollJumper } from "../../helpers";

const Home = () => {
  return (
    <section className="home-page container mx-auto d-flex align-start justify-center col">
      <h1 className="header-primary">
        <span>Hello</span>
        <span
          className="hand-emoji"
          role="img"
          aria-label="Apple Waving Hand Emoji"
        >
          👋
        </span>
        ,
      </h1>
      <h1 className="header-primary">
        I'm <span className="name">Christian Valdez</span>
      </h1>
      <h2 className="subtitle">Full Stack Developer</h2>
      <button
        onClick={() => scrollJumper("about")}
        className="home-btn btn-primary my-1"
      >
        About Me
      </button>
    </section>
  );
};

export default Home;
