// src/app/_components/Portfolio.tsx
import React from "react";
import Image from "next/image";
import { FaPaperPlane, FaGithub } from "react-icons/fa";
import twitterCloneScreenshot from "/public/images/twitterCloneScreenshot.png";
import portfolioScreenshot from "/public/images/portfolioScreenshot.png";
import coffeeTrackerScreenshot from "/public/images/coffeeScreenshot.png";
import iceCreamScreenshot from "/public/images/iceCreamScreenshot.png";
import todosScreenshot from "/public/images/todosScreenshot.png";

const projects = [
  {
    title: "Twitter Clone",
    description: `
          A feature rich twitter clone built with Vue.js on the frontend and
          Ruby on Rails for the backend. It has the ability to sign up and login
          users, tweet posting, follow and unfollowing of users, likes,
          retweets, and profile editing.
    `,
    image: twitterCloneScreenshot,
    siteLink: "https://twitter.chrisvaldez.dev",
    githubLink: "https://github.com/unChartedZone/twitter-clone",
  },
  {
    title: "My Portfolio!",
    description: `
            This very website you're on right now! Oringinally I built it with
            just HTML, CSS, and some Javascript, but later I converted it over
            to a Vue.js project. However I wanted to benefit from SEO and have
            faster static rendering, so I decided to convert it to a Next.js
            site instead. I also setup a Github Action that builds and deploys
            my portfolio when I push changes to my main branch.
          `,
    image: portfolioScreenshot,
    siteLink: "https://chrisvaldez.dev",
    githubLink: "https://github.com/unChartedZone/unChartedZone.github.io",
  },
  {
    title: "Coffee Tracker",
    description: `
            A Coffee Tracker app made with React that utilizes the Yelp API
            to fetch coffee places based on a given location and help you
            find the best coffe shop near you. The user can see their rating,
            and address to the restaurant/cafe. It utilizes Netlify
            serverless functions in order to talk to the Yelp API.
          `,
    image: coffeeTrackerScreenshot,
    siteLink: "https://coffee.chrisvaldez.dev",
    githubLink: "https://github.com/unChartedZone/coffee-tracker",
  },
  {
    title: "Ice Cream BMS",
    description: `
            This buisness management website was created as part of a school
            project. It was first built with Bootstrap, PHP, and MySQL, it
            featured crud operations on various tables and custom validation.
            It was hosted on a DigitalOcean droplet using Nginx as it's web
            server. Recently I converted it over to be a React app using
            firebase as it's backend and hosted on Netlify.
          `,
    image: iceCreamScreenshot,
    siteLink: "https://icecream.chrisvaldez.dev",
    githubLink: "https://github.com/unChartedZone/IceCreamIMS",
  },
  {
    title: "Todo App",
    description: `
            This Todo App features the ability to create collections of todos.
            Within each collection, a user can create, delete, and edit todos.
            This App also features user authentication using Firebase  and form
            validation using Vee Validate.
          `,
    image: todosScreenshot,
    siteLink: "https://todos.chrisvaldez.dev",
    githubLink: "https://github.com/unChartedZone/todo-app",
  },
];

interface ProjectProps {
  title: string;
  description: string;
  siteLink: string;
  githubLink: string;
  image: any;
}

const Project: React.FC<ProjectProps> = ({
  title,
  description,
  siteLink,
  githubLink,
  image,
}) => (
  <div className="portfolio__item">
    <div className="portfolio__header">
      <h1>
        <span className="portfolio__title">{title}</span>
      </h1>
    </div>
    <div className="portfolio__content">
      <div className="portfolio__image">
        {/* <Img fluid={fluid} /> */}
        <Image src={image} alt="Screenshot of twitter clone app" />
      </div>
      <div className="portfolio__body">
        <p className="portfolio__copy">{description}</p>
        <div>
          <a className="portfolio__link mr-1" href={siteLink} target="_blank">
            <span>
              <FaPaperPlane />
              Visit
            </span>
          </a>
          <a
            className="portfolio__link portfolio__link--outlined"
            href={githubLink}
            target="_blank"
          >
            <span>
              <FaGithub />
              Source
            </span>
          </a>
        </div>
      </div>
    </div>
  </div>
);

const Portfolio = () => {
  return (
    <section id="portfolio" className="portfolio-section my-4">
      <div className="container mx-auto d-flex col justify-center">
        <h2 className="header-secondary text-center">Projects</h2>
        <>
          {projects.map((project, index) => {
            return (
              <Project
                key={index}
                title={project.title}
                description={project.description}
                siteLink={project.siteLink}
                githubLink={project.githubLink}
                image={project.image}
              />
            );
          })}
        </>
      </div>
    </section>
  );
};

export default Portfolio;

// src/components/Portfolio.vue
<template>
  <section id="portfolio" class="portfolio-section my-4">
    <div class="container mx-auto d-flex col justify-center">
      <h2 class="header-secondary text-center">Portfolio</h2>
      <div
        class="portfolio__item"
        v-for="project in projects"
        :key="project.title"
      >
        <div class="portfolio__header">
          <h1>
            <span class="portfolio__title">{{ project.title }}</span>
          </h1>
        </div>
        <div class="portfolio__content">
          <div class="portfolio__image">
            <img :src="`${project.imgSrc}`" alt="" />
          </div>
          <div class="portfolio__body">
            <p class="portfolio__copy">{{ project.description }}</p>
            <div>
              <z-link class="mr-1" :url="project.siteLink">
                <i class="fas fa-paper-plane"></i>
                Visit
              </z-link>
              <z-link :url="project.githubLink" outlined>
                <i class="fab fa-github"></i>
                Source
              </z-link>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  data() {
    return {
      projects: [
        {
          title: 'My Portfolio!',
          description: `
            This very website you're on right now! I made this website with
            VueJS and have it hosted on Github Pages. Orginally my portfolio
            was built with only with vanilla HTML and CSS but over time it
            became hard to manage and update, with Vue I can easily swap out
            components and keep my portfolio up to date.
          `,
          imgSrc: require('@/assets/images/portfolioScreenshot.png'),
          siteLink: 'https://chrisvaldez.dev',
          githubLink:
            'https://github.com/unChartedZone/unChartedZone.github.io',
        },
        {
          title: 'Ice Cream Buisness Management System',
          description: `
            This buisness management website was created as part of a school
            project. It was first built with Bootstrap, PHP, and MySQL, it
            featured crud operations on various tables and custom validation.
            It was hosted on a DigitalOcean droplet using Nginx as it's web
            server. Recently I converted it over to be a React app using
            firebase as it's backend and hosted on Netlify.
          `,
          imgSrc: require('@/assets/images/iceCreamScreenshot.png'),
          siteLink: 'https://icecream.chrisvaldez.dev',
          githubLink:
            'https://github.com/unChartedZone/unChartedZone.github.io',
        },
        // {
        //   title: 'Weather App',
        //   description: '',
        //   imgSrc: require('@/assets/images/iceCreamScreenshot.png'),
        // },
        // {
        //   title: 'Todo App',
        //   description: '',
        //   imgSrc: require('@/assets/images/iceCreamScreenshot.png'),
        // },
      ],
    }
  },
}
</script>

<style lang="scss">
.portfolio {
  &__item {
    margin: 7rem 0;
    width: 100%;
  }

  &__header {
    text-align: center;
    margin: 0 0 3rem;
  }

  &__title {
    display: inline-block;
    background-color: $color-primary;
    color: #ffffff;
    font-size: 2rem;
    font-weight: 400;
    padding: 0.8rem;
    transform: skewY(-5deg);
    backface-visibility: hidden;
  }

  &__content {
    display: grid;
    grid-template-columns: 1fr 1fr;
  }

  &__image {
    padding: 0 2rem;

    img {
      border-radius: 7px;
      height: 100%;
      width: 100%;
      box-shadow: 4px 4px 10px 5px rgba(0, 0, 0, 0.5);
    }
  }

  &__body {
    font-size: 1.5rem;
    padding: 0 2rem;
    display: flex;
    flex-flow: row wrap;
    align-content: space-between;
  }

  &__copy {
    line-height: 1.7;
  }
}
</style>
